In [2]:
# !mkdir -p ~/.kaggle
# !cp kaggle.json ~/.kaggle/
!pip3 install tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/93/21/9b035a4f823d6aee2917c75415be9a95861ff3d73a0a65e48edbf210cec1/tensorflow-2.15.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.15.0 from https://files.pythonhosted.org/packages/4c/48/1a5a15517f18eaa4ff8d598b1c000300b20c1bb0e624539d702117a0c369/tensorflow_intel-2.15.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/01/e4/dc0a1dcc4e74e08d7abedab278c795eef54a224363bb18f5692f416d834f/absl_py-2.0.0-py3-none-any.whl.metadata
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl.metad

In [ ]:
# !kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

In [ ]:
# import zipfile
# zip_ref=zipfile.ZipFile('/content/chest-xray-pneumonia.zip','r')
# zip_ref.extractall('/content')
# zip_ref.close()

In [ ]:
import numpy as np
from sklearn.model_selection import KFold

X = np.array([[0., 0.], [1., 1.],[2., 2.],[3.0,3.0],[4.0,4.0],[5.0,5.0]])
y = np.array([0, 1, 0, 1,0,1])

kf = KFold(n_splits=3)
for train, test in kf.split(X):
    print("%s %s" % (train, test))
    X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]
    print(X_train, X_test, y_train, y_test, sep='\n')
    print()

[2 3 4 5] [0 1]
[[2. 2.]
 [3. 3.]
 [4. 4.]
 [5. 5.]]
[[0. 0.]
 [1. 1.]]
[0 1 0 1]
[0 1]

[0 1 4 5] [2 3]
[[0. 0.]
 [1. 1.]
 [4. 4.]
 [5. 5.]]
[[2. 2.]
 [3. 3.]]
[0 1 0 1]
[0 1]

[0 1 2 3] [4 5]
[[0. 0.]
 [1. 1.]
 [2. 2.]
 [3. 3.]]
[[4. 4.]
 [5. 5.]]
[0 1 0 1]
[0 1]



In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [1]:
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

from tensorflow import keras
from keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dropout, Flatten, BatchNormalization,Dense
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.utils import image_dataset_from_directory
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img
from tensorflow.keras.preprocessing import image_dataset_from_directory

import os
import matplotlib.image as mpimg


ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
import os

path = '/content/drive/MyDrive/Pneumonia Detection/chest_xray/train'

# Get classes without hidden files
classes = [c for c in os.listdir(path) if not c.startswith('.')]
print(classes[0])


NORMAL


In [ ]:
# Define the directories for the X-ray images
PNEUMONIA_dir = os.path.join(path + '/' + classes[1])
NORMAL_dir = os.path.join(path + '/' + classes[0])

# Create lists of the file names in each directory
pneumonia_names = os.listdir(PNEUMONIA_dir)
normal_names = os.listdir(NORMAL_dir)

print('There are ', len(pneumonia_names),
	'images of pneumonia infected in training dataset')
print('There are ', len(normal_names), 'normal images in training dataset')


There are  3875 images of pneumonia infected in training dataset
There are  1341 normal images in training dataset


In [ ]:
Train = keras.utils.image_dataset_from_directory(
	directory='/content/drive/MyDrive/Pneumonia Detection/chest_xray/train',
	labels="inferred",
	label_mode="categorical",
	batch_size=32,
	image_size=(256, 256))
Test = keras.utils.image_dataset_from_directory(
	directory='/content/drive/MyDrive/Pneumonia Detection/chest_xray/test',
	labels="inferred",
	label_mode="categorical",
	batch_size=32,
	image_size=(256, 256))
Validation = keras.utils.image_dataset_from_directory(
	directory='/content/drive/MyDrive/Pneumonia Detection/chest_xray/val',
	labels="inferred",
	label_mode="categorical",
	batch_size=32,
	image_size=(256, 256))


Found 5216 files belonging to 2 classes.
Found 624 files belonging to 2 classes.
Found 16 files belonging to 2 classes.


In [ ]:
tf.data.Dataset.from_tensor_slices(list(Train))

In [ ]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import KFold

# Assume you have a function that creates your model
def create_model():
    model=Sequential()
    model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Conv2D(64, (3, 3), activation='relu', input_shape=(256, 256, 3)))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Conv2D(64, (3, 3), activation='relu', input_shape=(256, 256, 3)))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Conv2D(64, (3, 3), activation='relu', input_shape=(256, 256, 3)))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Flatten())

    model.add(Dense(512, activation='relu'))
    model.add(Dropout(0.25))
    model.add(BatchNormalization())

    model.add(Dense(512, activation='relu'))
    model.add(Dropout(0.25))
    model.add(BatchNormalization())

    model.add(Dense(2, activation='sigmoid'))

    model.summary()


    model.compile(loss='binary_crossentropy',	optimizer='adam',	metrics=['accuracy'])
    return model

# # Specify the directory for your train and test data
train_directory = '/content/drive/MyDrive/Pneumonia Detection/chest_xray/train'
test_directory = '/content/drive/MyDrive/Pneumonia Detection/chest_xray/test'

# Use Keras' ImageDataGenerator to create a generator for test data
test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
    test_directory,
    target_size=(256, 256),
    batch_size=32,
    class_mode='categorical',
    shuffle=False  # No shuffling for the test dataset
)
test_data = np.array(list(test_generator))

# Specify the number of splits (k) for k-fold cross-validation
k = 5

# Use sklearn's KFold to split the data into k folds
kf = KFold(n_splits=k, shuffle=True, random_state=42)

for train_index, val_index in kf.split(train_generator.filenames):
    # Create new generators for training and validation sets
    train_data_generator = train_datagen.flow_from_directory(
        train_directory,
        target_size=(256, 256),
        batch_size=32,
        class_mode='categorical',
        shuffle=True,
        subset='training',
        indices=train_index
    )

    val_data_generator = train_datagen.flow_from_directory(
        train_directory,
        target_size=(256, 256),
        batch_size=32,
        class_mode='categorical',
        shuffle=True,
        subset='validation',
        indices=val_index
    )

    # Create and train the model
    model = create_model()

    model.fit(train_data_generator, epochs=5, validation_data=val_data_generator)
    #history = model.fit(Train,epochs=9,validation_data=Validation)

    # Evaluate the model on the test set
    test_loss, test_acc = model.evaluate(test_data[0], test_data[1])
    print(f'Test Accuracy: {test_acc}')

    # You can store or aggregate the results as needed


Found 624 images belonging to 2 classes.


In [ ]:
model=Sequential()

model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', input_shape=(256, 256, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', input_shape=(256, 256, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', input_shape=(256, 256, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())

model.add(Dense(512, activation='relu'))
model.add(Dropout(0.25))
model.add(BatchNormalization())

model.add(Dense(512, activation='relu'))
model.add(Dropout(0.25))
model.add(BatchNormalization())

model.add(Dense(2, activation='sigmoid'))

model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 254, 254, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2  (None, 127, 127, 32)      0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 125, 125, 64)      18496     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 62, 62, 64)        0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 60, 60, 64)        36928     
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 30, 30, 64)        0

In [ ]:
model.compile(loss='binary_crossentropy',	optimizer='adam',	metrics=['accuracy'])


In [ ]:
history = model.fit(Train,
		epochs=9,
		validation_data=Validation)


Epoch 1/9


In [ ]:
history_df = pd.DataFrame(history.history)
history_df.loc[:, ['loss', 'val_loss']].plot()
history_df.loc[:, ['accuracy', 'val_accuracy']].plot()
plt.show()
